# Calico Enterprise Version v3.13.1
# https://docs.tigera.io/v3.13/releases#v3.13.1

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tigera-federation-remote-cluster
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - serviceaccounts
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups: ["crd.projectcalico.org"]
  resources:
  - hostendpoints
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tigera-federation-remote-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tigera-federation-remote-cluster
subjects:
- kind: ServiceAccount
  name: tigera-federation-remote-cluster
  namespace: kube-system
