---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
    region: northeurope
    location: ireland
    geography: eu
    release-stage: prod
spec:
  containers:
  - image: ubuntu
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
