---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
    region: westeurope
    location: netherlands
    geography: eu
    release-stage: dev
spec:
  containers:
  - image: ubuntu
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
