---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
    region: eastus
    location: virgina
    geography: us
    release-stage: dev
    gdpr: "false"
spec:
  containers:
  - image: ubuntu
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
