---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  labels:
    app: netshoot
    region: westus2
    location: washington
    geography: us
    release-stage: prod
spec:
  containers:
  - image: nicolaka/netshoot
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
    name: netshoot
  restartPolicy: Always
