---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: my-app
  name: my-app
  namespace: my-app
spec:
  selector:
    run: my-app
  ports:
  - name: my-app-ui
    port: 80
    protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app
spec:
  selector:
    matchLabels:
      run: my-app
  replicas: 2
  template:
    metadata:
      labels:
        run: my-app
    spec:
      containers:
      - name: my-app
        image: nginx
        ports:
        - containerPort: 80
