apiVersion: v1
kind: Service
metadata:
  name: my-app-federated
  namespace: my-app
  annotations:
    federation.tigera.io/serviceSelector:
      run == "my-app"
spec:
  ports:
  - name: my-app-ui
    port: 80
    protocol: TCP
  type: ClusterIP
